### ISSUE TITLE
Error: Creating new datasource with Jaspersoft Studio 6.3.0 UnsupportedOperationException

### ISSUE THREAD

**Issue by cvitter** [basho-labs/Riak-TS-JDBC-Driver#13]
Receive the following error when attempting to query via the Riak TS JDBC driver:

java.lang.UnsupportedOperationException
    at com.basho.riakts.jdbc.Connection.prepareStatement(Connection.java:71)
    at net.sf.jasperreports.engine.query.JRJdbcQueryExecuter.createStatement(JRJdbcQueryExecuter.java:384)
    at net.sf.jasperreports.engine.query.JRJdbcQueryExecuter.createDatasource(JRJdbcQueryExecuter.java:297)
    at com.jaspersoft.studio.data.jdbc.JDBCFieldsProvider.getFields(JDBCFieldsProvider.java:79)
    at com.jaspersoft.studio.data.jdbc.JDBCDataAdapterDescriptor.getFields(JDBCDataAdapterDescriptor.java:75)
    at com.jaspersoft.studio.data.ui.SimpleQueryWizardDataEditorComposite.readFields(SimpleQueryWizardDataEditorComposite.java:241)
    at com.jaspersoft.studio.wizards.datasource.StaticWizardDataSourcePage.run(StaticWizardDataSourcePage.java:380)
    at com.jaspersoft.studio.wizards.JSSWizardRunnablePage$1.run(JSSWizardRunnablePage.java:81)
    at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)

**Comment by cvitter** [comment]
Need to implement prepareStatement, with implementation stubbed out we get new error:

java.lang.ClassCastException: com.basho.riakts.jdbc.Statement cannot be cast to java.sql.PreparedStatement
    at com.basho.riakts.jdbc.Connection.prepareStatement(Connection.java:73)
    at net.sf.jasperreports.engine.query.JRJdbcQueryExecuter.createStatement(JRJdbcQueryExecuter.java:384)
    at net.sf.jasperreports.engine.query.JRJdbcQueryExecuter.createDatasource(JRJdbcQueryExecuter.java:297)
    at com.jaspersoft.studio.data.jdbc.JDBCFieldsProvider.getFields(JDBCFieldsProvider.java:79)
    at com.jaspersoft.studio.data.jdbc.JDBCDataAdapterDescriptor.getFields(JDBCDataAdapterDescriptor.java:75)
    at com.jaspersoft.studio.data.ui.SimpleQueryWizardDataEditorComposite.readFields(SimpleQueryWizardDataEditorComposite.java:241)
    at com.jaspersoft.studio.wizards.datasource.StaticWizardDataSourcePage.run(StaticWizardDataSourcePage.java:380)
    at com.jaspersoft.studio.wizards.JSSWizardRunnablePage$1.run(JSSWizardRunnablePage.java:81)
    at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)

**Comment by cvitter** [comment]
Need to implement prepareStatement, with implementation stubbed out we get new error:

java.lang.ClassCastException: com.basho.riakts.jdbc.Statement cannot be cast to java.sql.PreparedStatement
	at com.basho.riakts.jdbc.Connection.prepareStatement(Connection.java:73)
	at net.sf.jasperreports.engine.query.JRJdbcQueryExecuter.createStatement(JRJdbcQueryExecuter.java:384)
	at net.sf.jasperreports.engine.query.JRJdbcQueryExecuter.createDatasource(JRJdbcQueryExecuter.java:297)
	at com.jaspersoft.studio.data.jdbc.JDBCFieldsProvider.getFields(JDBCFieldsProvider.java:79)
	at com.jaspersoft.studio.data.jdbc.JDBCDataAdapterDescriptor.getFields(JDBCDataAdapterDescriptor.java:75)
	at com.jaspersoft.studio.data.ui.SimpleQueryWizardDataEditorComposite.readFields(SimpleQueryWizardDataEditorComposite.java:241)
	at com.jaspersoft.studio.wizards.datasource.StaticWizardDataSourcePage.run(StaticWizardDataSourcePage.java:380)
	at com.jaspersoft.studio.wizards.JSSWizardRunnablePage$1.run(JSSWizardRunnablePage.java:81)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)

**Comment by cvitter** [comment]
Implemented PreparedStatement, next error received that needs to be resolved:

java.lang.NullPointerException
    at com.jaspersoft.studio.data.jdbc.JDBCFieldsProvider.getFields(JDBCFieldsProvider.java:84)
    at com.jaspersoft.studio.data.jdbc.JDBCDataAdapterDescriptor.getFields(JDBCDataAdapterDescriptor.java:75)
    at com.jaspersoft.studio.data.ui.SimpleQueryWizardDataEditorComposite.readFields(SimpleQueryWizardDataEditorComposite.java:241)
    at com.jaspersoft.studio.wizards.datasource.StaticWizardDataSourcePage.run(StaticWizardDataSourcePage.java:380)
    at com.jaspersoft.studio.wizards.JSSWizardRunnablePage$1.run(JSSWizardRunnablePage.java:81)
    at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)

**Comment by cvitter** [comment]
Error above appears to be due to not implementing a custom ResultSetMetaData, implementing for 0.5
