### ISSUE TITLE
Unable to get value for result set field "weight" of class java.lang.Object

### ISSUE THREAD

**Issue by cvitter** [basho-labs/Riak-TS-JDBC-Driver#15]
Error received when previewing report in Jaspersoft Studio:

net.sf.jasperreports.engine.JRException: net.sf.jasperreports.engine.JRException: Unable to get value for result set field "weight" of class java.lang.Object.
    at com.jaspersoft.studio.editor.preview.view.control.ReportControler.fillReport(ReportControler.java:537)
    at com.jaspersoft.studio.editor.preview.view.control.ReportControler.access$20(ReportControler.java:512)
    at com.jaspersoft.studio.editor.preview.view.control.ReportControler$5.run(ReportControler.java:393)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: net.sf.jasperreports.engine.JRException: Unable to get value for result set field "weight" of class java.lang.Object.
    at net.sf.jasperreports.engine.JRResultSetDataSource.getFieldValue(JRResultSetDataSource.java:344)
    at net.sf.jasperreports.engine.fill.JRFillDataset.setOldValues(JRFillDataset.java:1373)
    at net.sf.jasperreports.engine.fill.JRFillDataset.next(JRFillDataset.java:1274)
    at net.sf.jasperreports.engine.fill.JRFillDataset.next(JRFillDataset.java:1250)
    at net.sf.jasperreports.engine.fill.JRBaseFiller.next(JRBaseFiller.java:1056)
    at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillReport(JRVerticalFiller.java:113)
    at net.sf.jasperreports.engine.fill.JRBaseFiller.fill(JRBaseFiller.java:580)
    at net.sf.jasperreports.engine.fill.BaseFillHandle$ReportFill.run(BaseFillHandle.java:123)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 4
    at com.basho.riakts.jdbc.ResultSet.getObject(ResultSet.java:165)
    at net.sf.jasperreports.engine.JRResultSetDataSource.getFieldValue(JRResultSetDataSource.java:339)
    ... 8 more

**Comment by cvitter** [comment]
Bug related to index of array starting at 0 in code when JDBC expected the index to start at 1

**Comment by nandini162** [comment]
did you get the solution to this!?

**Comment by cvitter** [comment]
Yes the issue is closed because I fixed the issue in the related release.
